compute_environment: LOCAL_MACHINE
#deepspeed_config:
#  gradient_accumulation_steps: 2
#  gradient_clipping: 1.0
#  offload_optimizer_device: cpu
#  offload_param_device: cpu
#  "bf16": {
#    "enabled": true
#  }
#
#distributed_type: DEEPSPEED
#fsdp_config:
#  fsdp: "full_shard auto_wrap"
#  fsdp_transformer_layer_cls_to_wrap: 'BloomBlock'
machine_rank: 0
main_training_function: main
megatron_lm_config: { }
mixed_precision: 'bf16'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
use_cpu: true